### ISSUE TITLE
Wrong arguments passed to check_box_tag

### ISSUE THREAD

**Issue by lime** [subwindow/negative-captcha#44]
In [`negative_check_box_tag`](https://github.com/subwindow/negative-captcha/blob/master/lib/negative_captcha/view_helpers.rb#L58) the third argument passed to `check_box_tag` is an empty options hash by default. It should in fact [be the boolean determining whether the box is checked or not](http://apidock.com/rails/ActionView/Helpers/FormTagHelper/check_box_tag), and other options should come as the fourth argument.

Since an empty hash is truthy, the check box will always be checked. Likewise, no other options (classes etc) can be passed to the check box.

``` haml
- # Will always be checked
= f.negative_check_box_field(@captcha, :thingy)

- # Always checked, class is not passed through
= f.negative_check_box_field(@captcha, :thingy, class: 'foo')

- # ArgumentError, too many arguments
= f.negative_check_box_field(@captcha, :thingy, false, class: 'foo')

- # Workaround to get expected checked state (though still no other options)
= f.negative_check_box_field(@captcha, :thingy, @captcha.values[:thingy].present?)
```

**Comment by veezus** [comment]
We saw the same behavior. We started patching the bug, but changed tack when we read in the README that checkboxes can be left alone.

Here's the commit we had in place before we changed gears: https://github.com/veezuskreistinc/negative-captcha/commit/988b164ca3564b5032e9bb3d2b675a54b2c6d12a
